# Generated by Django 5.0 on 2024-06-11 21:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winners', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('losers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('winner_score', models.IntegerField(default=0, help_text='The score achieved by the winners')),
                ('loser_score', models.IntegerField(default=0, help_text='The score achieved by the losers')),
                ('date_played', models.DateTimeField(auto_now_add=True, help_text='Date and time when the match was played')),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
    ]
